### PR TITLE
Keep currency selected on back navigation

### LINKED ISSUE #10: Currency should keep selected on back navigation

### PR DESCRIPTION
**Pull request by KristianLentino99**
See [here](https://github.com/leonardoarcari/dcapal/issues/10) for the bug report.

Closes #10.

### CODE REVIEW

**Comment by leonardoarcari** [comment]
Thanks @KristianLentino99 for your interest in DcaPal! Didn't have time to look at your PR, will give it a try in the following days.

In the meantime, can you make sure it matches our codestyle by running? 

```
npm run format
```

Were you able to get an up and running local stack to test it?

Cheers! 🙂

**Comment by KristianLentino99** [comment]
Yeah, I've already tested the changes locally and seems ok 🤘. But I forgot to run the format command. I'll run it tomorrow 👌

Thanks to you for this amazing project, hotel to contribute more!

**Comment by KristianLentino99** [comment]
@leonardoarcari I've checked in the `package.json` of the project but I can't find the format command for NPM. Am I missing something?

**Comment by leonardoarcari** [comment]
Yeah my bad. Indeed the `format` command is available in `rc/0.3.0` branch only but it should be available to you. Maybe you just needed to sync up with upstream? Anyway, let me fix that for you.

**Comment by leonardoarcari** [comment]
@KristianLentino99 Done! Rebased on top of `rc/0.3.0` and applied formatting. FYI you can sync with upstream as follows:

```bash
git remote add upstream https://github.com/leonardoarcari/dcapal.git
git fetch upstream
git rebase upstream/rc/0.3.0 # Example of upstream sync
```

**Review by leonardoarcari — APPROVED** [review]

**Pull request merged**
